### ISSUE TITLE
What do I do?

### ISSUE THREAD

**Issue by PPPDUD** [CatalystDevOrg/Catalyst5#7]
The zip file contains a single file with no extension named "Catalyst". What do I do with this file?

**Comment by lemystic** [comment]
Currently, Catalyst releases are Linux only. Linux executables don't require a file extension to be runned

Also unrelated question: Why did you get banned?

**Comment by jdev082** [comment]
> The zip file contains a single file with no extension named "Catalyst". What do I do with this file?

@PPPDUD You can just git clone the code, run `pip/pip3 install -r requirements.txt` and run `src/main.py`.

**Comment by PPPDUD** [comment]
In response to your unrelated question: I got banned because SUI Lookup was
getting alerts too quickly and I didn't notice in time before it was banned.
